version: 2
build:
  os: ubuntu-24.04
  tools:
    ruby: "3.3"
  jobs:
    install:
      - gem install bundler
      - cd docs && bundle install
    build:
      html:
        - cd docs && ./readthedocs-build.sh
